/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author mckayvick
 */
public class AccuseWeapon extends javax.swing.JDialog {

    /**
     * Creates new form AccuseRoom
     */
    public AccuseWeapon(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weapons = new javax.swing.ButtonGroup();
        candlestick = new javax.swing.JRadioButton();
        dagger = new javax.swing.JRadioButton();
        revolver = new javax.swing.JRadioButton();
        rope = new javax.swing.JRadioButton();
        pipe = new javax.swing.JRadioButton();
        wrench = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 3, 3, 3));

        weapons.add(candlestick);
        candlestick.setText(game.Card.CANDLESTICK);
        candlestick.setPreferredSize(null);
        candlestick.setRolloverEnabled(false);
        getContentPane().add(candlestick);

        weapons.add(dagger);
        dagger.setText(game.Card.DAGGER);
        dagger.setPreferredSize(null);
        dagger.setRolloverEnabled(false);
        dagger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daggerActionPerformed(evt);
            }
        });
        getContentPane().add(dagger);

        weapons.add(revolver);
        revolver.setText(game.Card.REVOLVER);
        revolver.setPreferredSize(null);
        revolver.setRolloverEnabled(false);
        getContentPane().add(revolver);

        weapons.add(rope);
        rope.setText(game.Card.ROPE);
        rope.setPreferredSize(null);
        rope.setRolloverEnabled(false);
        getContentPane().add(rope);

        weapons.add(pipe);
        pipe.setText(game.Card.PIPE);
        pipe.setPreferredSize(null);
        pipe.setRolloverEnabled(false);
        getContentPane().add(pipe);

        weapons.add(wrench);
        wrench.setText(game.Card.WRENCH);
        wrench.setPreferredSize(null);
        wrench.setRolloverEnabled(false);
        getContentPane().add(wrench);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daggerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daggerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daggerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccuseWeapon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccuseWeapon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccuseWeapon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccuseWeapon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AccuseWeapon dialog = new AccuseWeapon(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton candlestick;
    private javax.swing.JRadioButton dagger;
    private javax.swing.JRadioButton pipe;
    private javax.swing.JRadioButton revolver;
    private javax.swing.JRadioButton rope;
    private javax.swing.ButtonGroup weapons;
    private javax.swing.JRadioButton wrench;
    // End of variables declaration//GEN-END:variables
}
