package ui;

import javax.swing.JPanel;

/**
 *
 * @author Vicki
 */
public class Application extends CluedoFrame {

    /**
     * Creates new form NewApplication
     */
    public Application() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	Controller c = new Controller(this);
        turnPanel = new ui.TurnPanel(c);
        playersPanel = new JPanel();
        playersPanel1 = new ui.PlayersPanel(c);
        deckPanel1 = new ui.DeckPanel(c);
        boardPanel = new ui.BoardPanel(c);
//        menuBar = new javax.swing.JMenuBar();
//        fileMenu = new javax.swing.JMenu();
//        openMenuItem = new javax.swing.JMenuItem();
//        saveMenuItem = new javax.swing.JMenuItem();
//        saveAsMenuItem = new javax.swing.JMenuItem();
//        exitMenuItem = new javax.swing.JMenuItem();
//        editMenu = new javax.swing.JMenu();
//        cutMenuItem = new javax.swing.JMenuItem();
//        copyMenuItem = new javax.swing.JMenuItem();
//        pasteMenuItem = new javax.swing.JMenuItem();
//        deleteMenuItem = new javax.swing.JMenuItem();
//        helpMenu = new javax.swing.JMenu();
//        contentsMenuItem = new javax.swing.JMenuItem();
//        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        playersPanel.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout playersPanelLayout = new javax.swing.GroupLayout(playersPanel);
        playersPanel.setLayout(playersPanelLayout);
        playersPanelLayout.setHorizontalGroup(
            playersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playersPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        playersPanelLayout.setVerticalGroup(
            playersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playersPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(playersPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        deckPanel1.setBackground(new java.awt.Color(153, 204, 0));

        javax.swing.GroupLayout deckPanel1Layout = new javax.swing.GroupLayout(deckPanel1);
        deckPanel1.setLayout(deckPanel1Layout);
        deckPanel1Layout.setHorizontalGroup(
            deckPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        deckPanel1Layout.setVerticalGroup(
            deckPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        boardPanel.setBackground(new java.awt.Color(255, 51, 51));
        boardPanel.setForeground(new java.awt.Color(220, 220, 220));

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout turnPanel1Layout = new javax.swing.GroupLayout(turnPanel);
        turnPanel.setLayout(turnPanel1Layout);
        turnPanel1Layout.setHorizontalGroup(
            turnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, turnPanel1Layout.createSequentialGroup()
                .addComponent(boardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(deckPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        turnPanel1Layout.setVerticalGroup(
            turnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, turnPanel1Layout.createSequentialGroup()
                .addGroup(turnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deckPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

//        fileMenu.setMnemonic('f');
//        fileMenu.setText("File");
//
//        openMenuItem.setMnemonic('o');
//        openMenuItem.setText("Open");
//        fileMenu.add(openMenuItem);
//
//        saveMenuItem.setMnemonic('s');
//        saveMenuItem.setText("Save");
//        fileMenu.add(saveMenuItem);
//
//        saveAsMenuItem.setMnemonic('a');
//        saveAsMenuItem.setText("Save As ...");
//        saveAsMenuItem.setDisplayedMnemonicIndex(5);
//        fileMenu.add(saveAsMenuItem);
//
//        exitMenuItem.setMnemonic('x');
//        exitMenuItem.setText("Exit");
//        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                exitMenuItemActionPerformed(evt);
//            }
//        });
//        fileMenu.add(exitMenuItem);
//
//        menuBar.add(fileMenu);
//
//        editMenu.setMnemonic('e');
//        editMenu.setText("Edit");
//
//        cutMenuItem.setMnemonic('t');
//        cutMenuItem.setText("Cut");
//        editMenu.add(cutMenuItem);
//
//        copyMenuItem.setMnemonic('y');
//        copyMenuItem.setText("Copy");
//        editMenu.add(copyMenuItem);
//
//        pasteMenuItem.setMnemonic('p');
//        pasteMenuItem.setText("Paste");
//        editMenu.add(pasteMenuItem);
//
//        deleteMenuItem.setMnemonic('d');
//        deleteMenuItem.setText("Delete");
//        editMenu.add(deleteMenuItem);
//
//        menuBar.add(editMenu);
//
//        helpMenu.setMnemonic('h');
//        helpMenu.setText("Help");
//
//        contentsMenuItem.setMnemonic('c');
//        contentsMenuItem.setText("Contents");
//        helpMenu.add(contentsMenuItem);
//
//        aboutMenuItem.setMnemonic('a');
//        aboutMenuItem.setText("About");
//        helpMenu.add(aboutMenuItem);
//
//        menuBar.add(helpMenu);
//
//        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(turnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(turnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                             
        System.exit(0);
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
//    private javax.swing.JMenuItem aboutMenuItem;
//    private javax.swing.JMenuItem saveAsMenuItem;
//    private javax.swing.JMenuItem saveMenuItem;
//    private javax.swing.JMenuItem contentsMenuItem;
//    private javax.swing.JMenuItem copyMenuItem;
//    private javax.swing.JMenuItem cutMenuItem;
//    private javax.swing.JMenuItem deleteMenuItem;
//    private javax.swing.JMenu editMenu;
//    private javax.swing.JMenuItem exitMenuItem;
//    private javax.swing.JMenu fileMenu;
//    private javax.swing.JMenu helpMenu;
//    private javax.swing.JMenuBar menuBar;
//    private javax.swing.JMenuItem openMenuItem;
//    private javax.swing.JMenuItem pasteMenuItem;
    private ui.DeckPanel deckPanel1;
    private ui.BoardPanel boardPanel;
    private JPanel playersPanel;
    private ui.PlayersPanel playersPanel1;
    private ui.TurnPanel turnPanel;
    // End of variables declaration                   

}
