package ui;


import java.awt.CardLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vicki
 */
public class CC extends javax.swing.JFrame {

    /**
     * Creates new form CluedoFrame
     */
    public CC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuItem1 = new javax.swing.JMenuItem();
        contents = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        setup = new javax.swing.JPanel();
        setupPanel = new javax.swing.JPanel();
        turn = new javax.swing.JPanel();
        boardPanel = new javax.swing.JPanel();
        playersPanel = new javax.swing.JPanel();
        deckPanel = new javax.swing.JPanel();
        deckContents = new javax.swing.JSplitPane();
        playerHand = new javax.swing.JScrollPane();
        handContents = new javax.swing.JPanel();
        playerNotebook = new javax.swing.JPanel();
        notesCharacter = new javax.swing.JPanel();
        char1 = new javax.swing.JCheckBox();
        char2 = new javax.swing.JCheckBox();
        char3 = new javax.swing.JCheckBox();
        char4 = new javax.swing.JCheckBox();
        char5 = new javax.swing.JCheckBox();
        char6 = new javax.swing.JCheckBox();
        notesWeapons = new javax.swing.JPanel();
        weapon1 = new javax.swing.JCheckBox();
        weapon2 = new javax.swing.JCheckBox();
        weapon3 = new javax.swing.JCheckBox();
        weapon4 = new javax.swing.JCheckBox();
        weapon5 = new javax.swing.JCheckBox();
        weapon6 = new javax.swing.JCheckBox();
        notesRooms = new javax.swing.JPanel();
        room1 = new javax.swing.JCheckBox();
        room2 = new javax.swing.JCheckBox();
        room3 = new javax.swing.JCheckBox();
        room4 = new javax.swing.JCheckBox();
        room5 = new javax.swing.JCheckBox();
        room6 = new javax.swing.JCheckBox();
        room7 = new javax.swing.JCheckBox();
        room8 = new javax.swing.JCheckBox();
        room9 = new javax.swing.JCheckBox();
        room10 = new javax.swing.JCheckBox();
        room11 = new javax.swing.JCheckBox();
        gameover = new javax.swing.JPanel();
        theEndPanel = new javax.swing.JPanel();
        theEndTitle = new javax.swing.JPanel();
        theEndText = new javax.swing.JLabel();
        theEndContents = new javax.swing.JPanel();
        winnerIcon = new javax.swing.JLabel();
        playerHasSolvedTheMurder = new javax.swing.JLabel();
        guiltyWeapon = new javax.swing.JLabel();
        guiltyCharacter = new javax.swing.JLabel();
        guiltyRoom = new javax.swing.JLabel();
        menubar = new javax.swing.JMenuBar();
        menu_h_game = new javax.swing.JMenu();
        menu_newgame = new javax.swing.JMenuItem();
        menu_endturn = new javax.swing.JMenuItem();
        menu_quit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menu_main = new javax.swing.JMenuItem();
        menu_setup = new javax.swing.JMenuItem();
        menu_turn = new javax.swing.JMenuItem();
        menu_end = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        contents.setLayout(new java.awt.CardLayout());

        menu.setMinimumSize(new java.awt.Dimension(800, 600));
        menu.setLayout(new java.awt.BorderLayout());
        contents.add(menu, "card2");

        setup.setBackground(new java.awt.Color(10, 10, 10));
        setup.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout setupPanelLayout = new javax.swing.GroupLayout(setupPanel);
        setupPanel.setLayout(setupPanelLayout);
        setupPanelLayout.setHorizontalGroup(
            setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        setupPanelLayout.setVerticalGroup(
            setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        setup.add(setupPanel, java.awt.BorderLayout.CENTER);

        contents.add(setup, "card5");

        turn.setBackground(new java.awt.Color(200, 200, 100));
        java.awt.GridBagLayout turnLayout = new java.awt.GridBagLayout();
        turnLayout.columnWidths = new int[] {610, 190};
        turnLayout.columnWeights = new double[] {0.8, 0.2};
        turn.setLayout(turnLayout);

        boardPanel.setBackground(new java.awt.Color(230, 230, 90));
        boardPanel.setMaximumSize(null);
        boardPanel.setMinimumSize(new java.awt.Dimension(610, 430));
        boardPanel.setPreferredSize(new java.awt.Dimension(610, 430));

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        turn.add(boardPanel, gridBagConstraints);

        playersPanel.setBackground(new java.awt.Color(180, 180, 40));
        playersPanel.setMaximumSize(null);
        playersPanel.setPreferredSize(new java.awt.Dimension(190, 480));

        javax.swing.GroupLayout playersPanelLayout = new javax.swing.GroupLayout(playersPanel);
        playersPanel.setLayout(playersPanelLayout);
        playersPanelLayout.setHorizontalGroup(
            playersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        playersPanelLayout.setVerticalGroup(
            playersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 184;
        gridBagConstraints.ipady = 480;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        turn.add(playersPanel, gridBagConstraints);

        deckPanel.setBackground(new java.awt.Color(80, 80, 10));
        deckPanel.setMaximumSize(null);

        deckContents.setDividerLocation(300);
        deckContents.setDividerSize(10);

        playerHand.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        handContents.setLayout(new java.awt.GridLayout(1, 0));
        playerHand.setViewportView(handContents);

        deckContents.setLeftComponent(playerHand);

        playerNotebook.setLayout(new javax.swing.BoxLayout(playerNotebook, javax.swing.BoxLayout.X_AXIS));

        notesCharacter.setLayout(new java.awt.GridLayout(3, 2));

        char1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        char1.setText("jCheckBox1");
        notesCharacter.add(char1);

        char2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        char2.setText("jCheckBox2");
        notesCharacter.add(char2);

        char3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        char3.setText("jCheckBox3");
        notesCharacter.add(char3);

        char4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        char4.setText("jCheckBox4");
        notesCharacter.add(char4);

        char5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        char5.setText("jCheckBox5");
        notesCharacter.add(char5);

        char6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        char6.setText("jCheckBox6");
        notesCharacter.add(char6);

        playerNotebook.add(notesCharacter);

        notesWeapons.setLayout(new java.awt.GridLayout(3, 2));

        weapon1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        weapon1.setText("jCheckBox1");
        notesWeapons.add(weapon1);

        weapon2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        weapon2.setText("jCheckBox2");
        notesWeapons.add(weapon2);

        weapon3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        weapon3.setText("jCheckBox3");
        notesWeapons.add(weapon3);

        weapon4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        weapon4.setText("jCheckBox4");
        notesWeapons.add(weapon4);

        weapon5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        weapon5.setText("jCheckBox5");
        notesWeapons.add(weapon5);

        weapon6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        weapon6.setText("jCheckBox6");
        notesWeapons.add(weapon6);

        playerNotebook.add(notesWeapons);

        notesRooms.setLayout(new java.awt.GridLayout(4, 3));

        room1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        room1.setText("jCheckBox1");
        room1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room1ActionPerformed(evt);
            }
        });
        notesRooms.add(room1);

        room2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        room2.setText("jCheckBox2");
        notesRooms.add(room2);

        room3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        room3.setText("jCheckBox3");
        notesRooms.add(room3);

        room4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        room4.setText("jCheckBox4");
        notesRooms.add(room4);

        room5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        room5.setText("jCheckBox5");
        notesRooms.add(room5);

        room6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        room6.setText("jCheckBox6");
        notesRooms.add(room6);

        room7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        room7.setText("jCheckBox7");
        notesRooms.add(room7);

        room8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        room8.setText("jCheckBox8");
        notesRooms.add(room8);

        room9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        room9.setText("jCheckBox9");
        notesRooms.add(room9);

        room10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        room10.setText("jCheckBox10");
        notesRooms.add(room10);

        room11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        room11.setText("jCheckBox11");
        notesRooms.add(room11);

        playerNotebook.add(notesRooms);

        deckContents.setRightComponent(playerNotebook);

        javax.swing.GroupLayout deckPanelLayout = new javax.swing.GroupLayout(deckPanel);
        deckPanel.setLayout(deckPanelLayout);
        deckPanelLayout.setHorizontalGroup(
            deckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deckContents)
        );
        deckPanelLayout.setVerticalGroup(
            deckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deckContents, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 211;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        turn.add(deckPanel, gridBagConstraints);

        contents.add(turn, "card3");

        gameover.setBackground(new java.awt.Color(200, 30, 30));

        theEndText.setText("The End!");

        javax.swing.GroupLayout theEndTitleLayout = new javax.swing.GroupLayout(theEndTitle);
        theEndTitle.setLayout(theEndTitleLayout);
        theEndTitleLayout.setHorizontalGroup(
            theEndTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theEndTitleLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(theEndText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        theEndTitleLayout.setVerticalGroup(
            theEndTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(theEndText, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        winnerIcon.setText("jLabel2");

        playerHasSolvedTheMurder.setText("Player has solved the murder!");

        guiltyWeapon.setText("jLabel4");

        guiltyCharacter.setText("jLabel5");

        guiltyRoom.setText("jLabel6");

        javax.swing.GroupLayout theEndContentsLayout = new javax.swing.GroupLayout(theEndContents);
        theEndContents.setLayout(theEndContentsLayout);
        theEndContentsLayout.setHorizontalGroup(
            theEndContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theEndContentsLayout.createSequentialGroup()
                .addGroup(theEndContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(theEndContentsLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(theEndContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(winnerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playerHasSolvedTheMurder, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(theEndContentsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(guiltyWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiltyCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiltyRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        theEndContentsLayout.setVerticalGroup(
            theEndContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theEndContentsLayout.createSequentialGroup()
                .addComponent(winnerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerHasSolvedTheMurder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(theEndContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guiltyWeapon, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(guiltyCharacter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guiltyRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout theEndPanelLayout = new javax.swing.GroupLayout(theEndPanel);
        theEndPanel.setLayout(theEndPanelLayout);
        theEndPanelLayout.setHorizontalGroup(
            theEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theEndPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(theEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(theEndTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(theEndContents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        theEndPanelLayout.setVerticalGroup(
            theEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theEndPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(theEndTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(theEndContents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout gameoverLayout = new javax.swing.GroupLayout(gameover);
        gameover.setLayout(gameoverLayout);
        gameoverLayout.setHorizontalGroup(
            gameoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameoverLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(theEndPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        gameoverLayout.setVerticalGroup(
            gameoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameoverLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(theEndPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        contents.add(gameover, "card4");

        menu_h_game.setText("Cluedo");

        menu_newgame.setText("New game");
        menu_newgame.setEnabled(false);
        menu_newgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_newgameActionPerformed(evt);
            }
        });
        menu_h_game.add(menu_newgame);

        menu_endturn.setText("End turn");
        menu_endturn.setEnabled(false);
        menu_endturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_endturnActionPerformed(evt);
            }
        });
        menu_h_game.add(menu_endturn);

        menu_quit.setText("Quit");
        menu_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_quitActionPerformed(evt);
            }
        });
        menu_h_game.add(menu_quit);

        menubar.add(menu_h_game);

        jMenu1.setText("jMenu1");

        menu_main.setText("Main");
        menu_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_mainActionPerformed(evt);
            }
        });
        jMenu1.add(menu_main);

        menu_setup.setText("Setup");
        menu_setup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_setupActionPerformed(evt);
            }
        });
        jMenu1.add(menu_setup);

        menu_turn.setText("Turn");
        menu_turn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_turnActionPerformed(evt);
            }
        });
        jMenu1.add(menu_turn);

        menu_end.setText("End");
        menu_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_endTurnActionPerformed(evt);
            }
        });
        jMenu1.add(menu_end);

        menubar.add(jMenu1);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contents, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contents, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void menu_endturnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        ((CardLayout)(contents.getLayout())).show(contents, "card");
    }                                            

    private void menu_newgameActionPerformed(java.awt.event.ActionEvent evt) {                                             
        ((CardLayout)(contents.getLayout())).show(contents, "card");
    }                                            

    private void menu_quitActionPerformed(java.awt.event.ActionEvent evt) {                                          
        System.exit(0);
    }                                         

    private void room1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void menu_setupActionPerformed(java.awt.event.ActionEvent evt) {                                           
        ((CardLayout)(contents.getLayout())).show(contents, "card5");
    }                                          

    private void menu_endTurnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void menu_mainActionPerformed(java.awt.event.ActionEvent evt) {                                          
        ((CardLayout)(contents.getLayout())).show(contents, "card2");
    }                                         

    private void menu_turnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        ((CardLayout)(contents.getLayout())).show(contents, "card3");
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CluedoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CluedoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CluedoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CluedoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CluedoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel boardPanel;
    private javax.swing.JCheckBox char1;
    private javax.swing.JCheckBox char2;
    private javax.swing.JCheckBox char3;
    private javax.swing.JCheckBox char4;
    private javax.swing.JCheckBox char5;
    private javax.swing.JCheckBox char6;
    private javax.swing.JPanel contents;
    private javax.swing.JSplitPane deckContents;
    private javax.swing.JPanel deckPanel;
    private javax.swing.JPanel gameover;
    private javax.swing.JLabel guiltyCharacter;
    private javax.swing.JLabel guiltyRoom;
    private javax.swing.JLabel guiltyWeapon;
    private javax.swing.JPanel handContents;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel menu;
    private javax.swing.JMenuItem menu_end;
    private javax.swing.JMenuItem menu_endturn;
    private javax.swing.JMenu menu_h_game;
    private javax.swing.JMenuItem menu_main;
    private javax.swing.JMenuItem menu_newgame;
    private javax.swing.JMenuItem menu_quit;
    private javax.swing.JMenuItem menu_setup;
    private javax.swing.JMenuItem menu_turn;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JPanel notesCharacter;
    private javax.swing.JPanel notesRooms;
    private javax.swing.JPanel notesWeapons;
    private javax.swing.JScrollPane playerHand;
    private javax.swing.JLabel playerHasSolvedTheMurder;
    private javax.swing.JPanel playerNotebook;
    private javax.swing.JPanel playersPanel;
    private javax.swing.JCheckBox room1;
    private javax.swing.JCheckBox room10;
    private javax.swing.JCheckBox room11;
    private javax.swing.JCheckBox room2;
    private javax.swing.JCheckBox room3;
    private javax.swing.JCheckBox room4;
    private javax.swing.JCheckBox room5;
    private javax.swing.JCheckBox room6;
    private javax.swing.JCheckBox room7;
    private javax.swing.JCheckBox room8;
    private javax.swing.JCheckBox room9;
    private javax.swing.JPanel setup;
    private javax.swing.JPanel setupPanel;
    private javax.swing.JPanel theEndContents;
    private javax.swing.JPanel theEndPanel;
    private javax.swing.JLabel theEndText;
    private javax.swing.JPanel theEndTitle;
    private javax.swing.JPanel turn;
    private javax.swing.JCheckBox weapon1;
    private javax.swing.JCheckBox weapon2;
    private javax.swing.JCheckBox weapon3;
    private javax.swing.JCheckBox weapon4;
    private javax.swing.JCheckBox weapon5;
    private javax.swing.JCheckBox weapon6;
    private javax.swing.JLabel winnerIcon;
    // End of variables declaration                   
}
