/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Set;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author mckayvick
 */
public class GameSetupPanel extends javax.swing.JDialog {
    private class Pair {
        String name = null;
        String plays = null;
        Pair (String name, String chara) {
            this.name = name;
            this.plays = chara;
        }
        String name () { return name; }
        String plays() { return plays; }
        void name(String n) { name = n; }
        void plays(String p) { plays = p; }
    }
    
    private Set<Pair> futurePlayers = new HashSet<Pair>();
    
    /**
     * Creates new form GameSetupPanel
     */
    public GameSetupPanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        charSelect = new javax.swing.ButtonGroup();
        NameSelection = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextInput = new javax.swing.JTextField();
        selectPanel = new javax.swing.JPanel();
        scarlet = new javax.swing.JRadioButton();
        mustard = new javax.swing.JRadioButton();
        white = new javax.swing.JRadioButton();
        green = new javax.swing.JRadioButton();
        peacock = new javax.swing.JRadioButton();
        plum = new javax.swing.JRadioButton();
        submitPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        textPanel = new javax.swing.JPanel();

        setTitle("Player Setup");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(435, 526));
        setSize(new java.awt.Dimension(435, 516));

        nameLabel.setText("Enter your name:");

        nameTextInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameTextInput.setMinimumSize(new java.awt.Dimension(4, 4));
        nameTextInput.setName("name"); // NOI18N
        nameTextInput.setNextFocusableComponent(scarlet);
        nameTextInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NameSelectionLayout = new javax.swing.GroupLayout(NameSelection);
        NameSelection.setLayout(NameSelectionLayout);
        NameSelectionLayout.setHorizontalGroup(
            NameSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameTextInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(NameSelectionLayout.createSequentialGroup()
                .addComponent(nameLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        NameSelectionLayout.setVerticalGroup(
            NameSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NameSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        selectPanel.setLayout(new java.awt.GridLayout(2, 3, 0, 3));

        charSelect.add(scarlet);
        scarlet.setAlignmentX(0.5F);
        scarlet.setBorderPainted(true);
        scarlet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scarlet.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/scarlet_s.png"))); // NOI18N
        scarlet.setHideActionText(true);
        scarlet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scarlet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        scarlet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/scarlet.png"))); // NOI18N
        scarlet.setNextFocusableComponent(mustard);
        scarlet.setOpaque(false);
        scarlet.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/scarlet.png"))); // NOI18N
        scarlet.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/scarlet_c.png"))); // NOI18N
        scarlet.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/scarlet_c.png"))); // NOI18N
        scarlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scarletActionPerformed(evt);
            }
        });
        selectPanel.add(scarlet);

        charSelect.add(mustard);
        mustard.setAlignmentX(0.5F);
        mustard.setBorderPainted(true);
        mustard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mustard.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/mustard_s.png"))); // NOI18N
        mustard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mustard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/mustard.png"))); // NOI18N
        mustard.setNextFocusableComponent(white);
        mustard.setOpaque(false);
        mustard.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/mustard.png"))); // NOI18N
        mustard.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/mustard_c.png"))); // NOI18N
        mustard.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/mustard_c.png"))); // NOI18N
        selectPanel.add(mustard);

        charSelect.add(white);
        white.setAlignmentX(0.5F);
        white.setBorderPainted(true);
        white.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        white.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/white_s.png"))); // NOI18N
        white.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        white.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/white.png"))); // NOI18N
        white.setNextFocusableComponent(green);
        white.setOpaque(false);
        white.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/white.png"))); // NOI18N
        white.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/white_c.png"))); // NOI18N
        white.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/white_c.png"))); // NOI18N
        white.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteActionPerformed(evt);
            }
        });
        selectPanel.add(white);

        charSelect.add(green);
        green.setAlignmentX(0.5F);
        green.setBorderPainted(true);
        green.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        green.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/green_s.png"))); // NOI18N
        green.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        green.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        green.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/green.png"))); // NOI18N
        green.setNextFocusableComponent(peacock);
        green.setOpaque(false);
        green.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/green.png"))); // NOI18N
        green.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/green_c.png"))); // NOI18N
        green.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/green_c.png"))); // NOI18N
        selectPanel.add(green);

        charSelect.add(peacock);
        peacock.setAlignmentX(0.5F);
        peacock.setBorderPainted(true);
        peacock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peacock.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/peacock_s.png"))); // NOI18N
        peacock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        peacock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/peacock.png"))); // NOI18N
        peacock.setNextFocusableComponent(plum);
        peacock.setOpaque(false);
        peacock.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/peacock.png"))); // NOI18N
        peacock.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/peacock_c.png"))); // NOI18N
        peacock.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/peacock_c.png"))); // NOI18N
        selectPanel.add(peacock);

        charSelect.add(plum);
        plum.setAlignmentX(0.5F);
        plum.setBorderPainted(true);
        plum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plum.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/plum_s.png"))); // NOI18N
        plum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/plum.png"))); // NOI18N
        plum.setNextFocusableComponent(okButton);
        plum.setOpaque(false);
        plum.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/plum.png"))); // NOI18N
        plum.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/plum_c.png"))); // NOI18N
        plum.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/plum_c.png"))); // NOI18N
        selectPanel.add(plum);

        okButton.setText("OK");
        okButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okButton.setNextFocusableComponent(((futurePlayers.size() < 3)) ? (nameTextInput) : (startButton)
        );
        okButton.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                submitCharacter(evt);
            }
        });

        startButton.setText("Start Game");
        startButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout submitPanelLayout = new javax.swing.GroupLayout(submitPanel);
        submitPanel.setLayout(submitPanelLayout);
        submitPanelLayout.setHorizontalGroup(
            submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitPanelLayout.createSequentialGroup()
                .addComponent(okButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startButton))
        );
        submitPanelLayout.setVerticalGroup(
            submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submitPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(startButton))
                .addContainerGap())
        );

        textPanel.setToolTipText("This will be the character you play as during the game.");
        textPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        textPanel.setOpaque(false);

        javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameSelection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("GameSetup");
        getAccessibleContext().setAccessibleDescription("Select your player name and character.");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitCharacter(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_submitCharacter
        // TODO add your handling code here:
        System.out.print("hi ");
        if (true) { // if the button has been pressed...
            String player = nameTextInput.getText();
            for (char c : player.toCharArray()) {
                if (!Character.isLetterOrDigit(c) || !Character.isWhitespace(c)) {
                    JOptionPane optionPane = new JOptionPane("message",JOptionPane.QUESTION_MESSAGE,JOptionPane.YES_NO_OPTION);
                    JDialog dialog = new JDialog(new JFrame(), "Click a button", true);
                    dialog.setContentPane(optionPane);
                    dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
                    optionPane.addPropertyChangeListener(
                        new PropertyChangeListener() {
                            public void propertyChange(PropertyChangeEvent e) {
                                String prop = e.getPropertyName();

                                if (dialog.isVisible() 
                                 && (e.getSource() == optionPane)
                                 && (prop.equals(JOptionPane.VALUE_PROPERTY))) {
                                    // do something
                                    dialog.setVisible(false);
                                }
                            };
                    });
                    dialog.pack();
                    dialog.setVisible(true);
                    dialog.setAlwaysOnTop(true);
                }
            }
        }
    }//GEN-LAST:event_submitCharacter

    private void whiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whiteActionPerformed

    private void scarletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scarletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scarletActionPerformed

    private void nameTextInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameSetupPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameSetupPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameSetupPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameSetupPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameSetupPanel dialog = new GameSetupPanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NameSelection;
    private javax.swing.ButtonGroup charSelect;
    private javax.swing.JRadioButton green;
    private javax.swing.JRadioButton mustard;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextInput;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton peacock;
    private javax.swing.JRadioButton plum;
    private javax.swing.JRadioButton scarlet;
    private javax.swing.JPanel selectPanel;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel submitPanel;
    private javax.swing.JPanel textPanel;
    private javax.swing.JRadioButton white;
    // End of variables declaration//GEN-END:variables
}
