/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author mckayvick
 */
public class GameSetupPanel extends javax.swing.JDialog {

    /**
     * Creates new form GameSetupPanel
     */
    public GameSetupPanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        charSelect = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        buttonGroup1 = new javax.swing.ButtonGroup();
        selectLabel = new javax.swing.JLabel();
        NameSelection = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextInput = new javax.swing.JTextField();
        selectPanel = new javax.swing.JPanel();
        scarlet = new javax.swing.JRadioButton();
        mustard = new javax.swing.JRadioButton();
        white = new javax.swing.JRadioButton();
        green = new javax.swing.JRadioButton();
        peacock = new javax.swing.JRadioButton();
        plum = new javax.swing.JRadioButton();
        submitPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton3.setText("jButton3");

        selectLabel.setText("Select a character:");

        setTitle("Cluedo Setup");
        setBackground(new java.awt.Color(204, 204, 255));

        nameLabel.setText("Enter your name:");

        nameTextInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameTextInput.setMinimumSize(new java.awt.Dimension(4, 4));
        nameTextInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NameSelectionLayout = new javax.swing.GroupLayout(NameSelection);
        NameSelection.setLayout(NameSelectionLayout);
        NameSelectionLayout.setHorizontalGroup(
            NameSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NameSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NameSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NameSelectionLayout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(nameTextInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        NameSelectionLayout.setVerticalGroup(
            NameSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NameSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        selectPanel.setLayout(new java.awt.GridLayout(2, 3, 0, 3));

        charSelect.add(scarlet);
        scarlet.setAlignmentX(0.5F);
        scarlet.setBorderPainted(true);
        scarlet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scarlet.setDisabledIcon(null);
        scarlet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scarlet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        scarlet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/scarlet.png"))); // NOI18N
        scarlet.setNextFocusableComponent(mustard);
        scarlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scarletActionPerformed(evt);
            }
        });
        selectPanel.add(scarlet);

        charSelect.add(mustard);
        mustard.setAlignmentX(0.5F);
        mustard.setBorderPainted(true);
        mustard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mustard.setDisabledIcon(null);
        mustard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mustard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/mustard.png"))); // NOI18N
        mustard.setNextFocusableComponent(white);
        mustard.setOpaque(false);
        selectPanel.add(mustard);

        charSelect.add(white);
        white.setAlignmentX(0.5F);
        white.setBorderPainted(true);
        white.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        white.setDisabledIcon(null);
        white.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        white.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/white.png"))); // NOI18N
        white.setNextFocusableComponent(green);
        white.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteActionPerformed(evt);
            }
        });
        selectPanel.add(white);

        charSelect.add(green);
        green.setAlignmentX(0.5F);
        green.setBorderPainted(true);
        green.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        green.setDisabledIcon(null);
        green.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        green.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        green.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/green.png"))); // NOI18N
        green.setNextFocusableComponent(peacock);
        selectPanel.add(green);

        charSelect.add(peacock);
        peacock.setAlignmentX(0.5F);
        peacock.setBorderPainted(true);
        peacock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peacock.setDisabledIcon(null);
        peacock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        peacock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/peacock.png"))); // NOI18N
        peacock.setNextFocusableComponent(plum);
        selectPanel.add(peacock);

        charSelect.add(plum);
        plum.setAlignmentX(0.5F);
        plum.setBorderPainted(true);
        plum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plum.setDisabledIcon(null);
        plum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/plum.png"))); // NOI18N
        plum.setNextFocusableComponent(okButton);
        selectPanel.add(plum);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        startButton.setText("Start Game");

        javax.swing.GroupLayout submitPanelLayout = new javax.swing.GroupLayout(submitPanel);
        submitPanel.setLayout(submitPanelLayout);
        submitPanelLayout.setHorizontalGroup(
            submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(okButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 542, Short.MAX_VALUE)
                .addComponent(startButton)
                .addContainerGap())
        );
        submitPanelLayout.setVerticalGroup(
            submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submitPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(startButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NameSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(submitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("GameSetup");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextInputActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okButtonActionPerformed

    private void scarletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scarletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scarletActionPerformed

    private void whiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameSetupPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameSetupPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameSetupPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameSetupPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameSetupPanel dialog = new GameSetupPanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NameSelection;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup charSelect;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JRadioButton green;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JRadioButton mustard;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextInput;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton peacock;
    private javax.swing.JRadioButton plum;
    private javax.swing.JRadioButton scarlet;
    private javax.swing.JLabel selectLabel;
    private javax.swing.JPanel selectPanel;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel submitPanel;
    private javax.swing.JRadioButton white;
    // End of variables declaration//GEN-END:variables
}
